### ISSUE TITLE
Document how to add custom root certificate for node.js

### ISSUE THREAD

**Issue by dgcom** [newrelic-experimental/nr-find-log4j#13]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

If scan is performed from behind SSL intercepting proxy, it may fail with the following error:
```
Exception processing API call: Error: self signed certificate in certificate chain
Error requesting accessible accounts from New Relic api.
```

This happens because node.js may not trust custom CA root certificate used to sign server certificate "substituted" by proxy.

## Desired Behavior

Scan should try handle this gracefully, possibly providing certificate details in the error.

## Possible solution

Either disable certificate check in the script or document that setting the following environment variable to the path with proxy's root certificate in PEM format will resolve the issue.
Example:
```shell
export NODE_EXTRA_CA_CERTS=~/proxy-ca-root.pem
node nr-find-log4j.js
```

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

Not all people scanning their Java deployments are fully aware how to fix such issue in node.js

**Comment by fightingmonk** [comment]
Thanks for reporting this issue @dgcom . If you have the environment, I could use help testing whether PR #14 correctly identifies this situation - I don't have a suitable proxy setup to test the cases of 1) a self-signed ssl certificate, or 2) a private root CA certificate not in Node's default cert store.

**Comment by dgcom** [comment]
Hello.

Yes, I have this setup and I have tested the changes in the PR.
The attempt to scan via such proxy now results in quite an informative error message:

```
Checking api key...

Uh oh, I think you're behind an HTTPS proxy with a self-signed or internal
certificate, which can cause Node.js requests to the New Relic API to fail.

CAUTION: Someone could be maliciously intercepting your network traffic.

If you're sure this is a trusted proxy, you can work around this issue:
1. Set the NODE_EXTRA_CA_CERTS environment variable to reference a PEM file
containing your proxy's certificate chain:
        NODE_EXTRA_CA_CERTS=proxy-ca-root-cert.pem node nr-find-log4j.js
2. Use the *unadvisable* NODE_TLS_REJECT_UNAUTHORIZED environment variable to
disable SSL certificate validation.

See the Node.js docs for help: https://nodejs.org/api/cli.html
```

I love this, the only thing I'd suggest to change is to provide a value for "unadvisable" variable :
```
2. Set the *unadvisable* NODE_TLS_REJECT_UNAUTHORIZED=0 environment variable to
disable SSL certificate validation.
```
