### ISSUE TITLE
Add EU data centre support switch

### ISSUE THREAD

**Issue by jsbnr** [newrelic-experimental/nr-find-log4j#4]
The script is hard coded to US data centre, please provide option to choose EU data centre api/s via command line. 

## Desired Behavior

Data centre can be selected with runtime  argument.

## Possible Solution

Current work around is to hard code the url here: 
const NERDGRAPH_URL = 'https://api.**eu.**newrelic.com/graphql';

**Comment by fightingmonk** [comment]
Fixed in #7 . Many thanks for flagging this and providing a temp workaround @jsbnr !
